
version: '3' 
services:
  nifi:
    #image: fjardim/mds-nifi
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    volumes:
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/certificado:/certificado
      - ./nifi/util:/util
      - ./scripts:/scripts
      - ./nifi/conf:/opt/nifi/nifi-current/conf
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"
      SINGLE_USER_CREDENTIALS_USERNAME: "nifiadmin"
      SINGLE_USER_CREDENTIALS_PASSWORD: "nifiadmin2023"
      KEYSTORE_PATH=: /certificado/keystore.jks 
      KEYSTORE_TYPE: JKS 
      KEYSTORE_PASSWORD: K3SFOTf1L5lqD+7grZKTmnQ3q2JEuYSpNIzLJ1UTsT8
      TRUSTSTORE_PATH=: /certificado/truststore.jks 
      TRUSTSTORE_PASSWORD: g7frQPylGzHOvb+3fK9EnMzMZ+CvrEZb8pkM7HvXkps 
      TRUSTSTORE_TYPE: JKS 
    ports:
      - "8443:8443"
    deploy:
      resources:
        limits:
          memory: 2048m

  mysql:
    image: mysql
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/db:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: "mysql"



